# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: The Logrus Songbook

owner: Pamela Mclean
email: pamela@logrus.ca

description: > # this means to ignore newlines until "baseurl:"

  All our favourite tunes from the whole spectrum of Shadows
baseurl:  /Songbook
lang: "en"
#url: "https://localhost:4000" # the base hostname & protocol for your site
url: "https://logrus.ca" # the base hostname & protocol for your site

twitter_username:
github_username:
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: <!--more-->


collections:
   tunes:
       output: true
        
defaults:
  - scope:
      path: ""
      type: "tunes"
    values:
      layout: "tune"
  - scope:
      path: ""
    values:
      layout: "default"


# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
